POST http://localhost:3000/api/superheroes HTTP/1.1
Content-Type: application/json

{
  "nickname": "SuperTester OMEGA",
  "realName": "Test Testovich",
  "originDescription": "He was born on undefined street, and since gained power of NULL",
  "catchPhrase": "I will Null You!",
  "superpowers": ["test power 1", "test power 2"]
}